[tool.briefcase]
project_name = "Picfix App"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/picfixapp"
license = "BSD license"
author = 'Ariel Mitnick'
author_email = "ariel.s.mitnick@gmail.com"

[tool.briefcase.app.picfixapp]
formal_name = "Picfix App"
description = "Remove photo background"
icon = "src/picfixapp/resources/picfixapp"
sources = ['src/picfixapp']
requires = []


[tool.briefcase.app.picfixapp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.picfixapp.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.picfixapp.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.picfixapp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.picfixapp.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
